[package]
name = "tangram_util"

description = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tangram_error = { workspace = true }
tokio = { workspace = true }
